[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
command = "rustup"
args = ["run", "nightly", "cargo", "fmt"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.build-all]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
